version: "3.9"
services:
  proxy:
    volumes:
    - ./templates:/etc/nginx/templates
    image: nginx
    ports:
      - 8081:4000
    environment:
    - HOSTNAME=localhost
    - PORT=4000
    - WEB_PORT=8080
    - PROXY_HOST=host.docker.internal
