apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: canary-marketplace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Marketplace App
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the marketplace namespace in the same cluster
  destinations:
  - namespace: canary-marketplace
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Service
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: networking.k8s.io
    kind: Ingress
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to canary-marketplace
    policies:
    - p, proj:canary-marketplace:read-only, applications, get, canary-marketplace/*, allow
    groups:
    - my-oidc-group
