export const ADDRESSES = {
  SKELETON_CREW: 'Bhr9iWx7vAZ4JDD5DVSdHxQLqG9RvCLCSXvu6yC4TF6c',
  ZEN0VERSE: '3wzFmJEHT3pfFukQPi9T73NCLb52qyvaKgEztumtTCJU',
  LONGHARBOR: '9QyeH5pmnNEWqnHzNtoeDFn8QVwVgvdvuNKu6TfHiJgg',
  CURSED_MIKES: '2QkXNKFB64x2vezfw5XLdWqhSwGr83Gs6MWD2gqfDcpE',
  DARKELV: '3oPa5K78fGusBgd2LtPE65e7AZuADJPadqrtqgWxmKLA',
  DUPLICATE_COLLECTION: '4cUyDakNPeMEZtJPDJGNujWLGF1XNH7WbQnheUEfD2xX',
}
